export enum Role {
  CEO = "CEO",
  ADMIN = "ADMIN",
  BAKER = "BAKER",
  DRIVER = "DRIVER",
  SUPPLIER = "SUPPLIER",
  DIVIDER = "DIVIDER",
  CUSTOMER = "CUSTOMER",
  DOUGHMAKER = "DOUGHMAKER",
  DISPETCHER = "DISPETCHER",
}
